version: '3.8'

services:
  php-fpm:
    build:
      context: ./.dev/php-fpm
    pull_policy: never
    image: lc-php-fpm
    container_name: lc_php-fpm
    restart: "unless-stopped"
    volumes:
      - ./src:/srv
    ports:
      - "8000:8000"
      - "5173:5173"
